### ISSUE TITLE
Add support for Node 10

### ISSUE THREAD

**Issue by AjayPoshak** [strongloop/strong-soap#207]
Not working on Node 10
# Description/Steps to reproduce

# Link to reproduction sandbox
 Please run `npm install` on Node version `10.15.1` to reproduce the bug.

# Additional information
Error details
```
warning Error running install script for optional dependency: "/Users/Ajay/Sites/Merch/comlib/node_modules/ursa: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/Ajay/Sites/Merch/comlib/node_modules/ursa
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.1 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/Ajay/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Ajay/Sites/Merch/comlib/node_modules/ursa/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Ajay/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Ajay/.node-gyp/10.15.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/Ajay/.node-gyp/10.15.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/Ajay/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/Ajay/.node-gyp/10.15.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/Ajay/Sites/Merch/comlib/node_modules/ursa',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
../src/ursaNative.cc:389:13: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    obj->rsa->n = BN_bin2bn(data_n, n_length, NULL);
            ^
/Users/Ajay/.node-gyp/10.15.1/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:390:13: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    obj->rsa->e = BN_bin2bn(data_e, e_length, NULL);
            ^
/Users/Ajay/.node-gyp/10.15.1/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:407:35: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    if ((obj == NULL) || (obj->rsa->d != NULL)) {
                                  ^
/Users/Ajay/.node-gyp/10.15.1/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:488:32: warning: 'Uint32Value' is deprecated [-Wdeprecated-declarations]
    int modulusBits = args[0]->Uint32Value();
                               ^
/Users/Ajay/.node-gyp/10.15.1/include/node/v8.h:2477:3: note: 'Uint32Value' has been explicitly marked deprecated here
  V8_DEPRECATED(\"Use maybe version\", uint32_t Uint32Value() const);
  ^
/Users/Ajay/.node-gyp/10.15.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/ursaNative.cc:489:29: warning: 'Uint32Value' is deprecated [-Wdeprecated-declarations]
    int exponent = args[1]->Uint32Value();
                            ^
/Users/Ajay/.node-gyp/10.15.1/include/node/v8.h:2477:3: note: 'Uint32Value' has been explicitly marked deprecated here
  V8_DEPRECATED(\"Use maybe version\", uint32_t Uint32Value() const);
  ^
/Users/Ajay/.node-gyp/10.15.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/ursaNative.cc:536:34: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    bignumToBuffer(args, obj->rsa->e);
                                 ^
/Users/Ajay/.node-gyp/10.15.1/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:552:34: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    bignumToBuffer(args, obj->rsa->d);
                                 ^
/Users/Ajay/.node-gyp/10.15.1/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:567:34: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    bignumToBuffer(args, obj->rsa->n);
                                 ^
/Users/Ajay/.node-gyp/10.15.1/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:683:28: warning: 'Uint32Value' is deprecated [-Wdeprecated-declarations]
    int padding = args[1]->Uint32Value();
                           ^
/Users/Ajay/.node-gyp/10.15.1/include/node/v8.h:2477:3: note: 'Uint32Value' has been explicitly marked deprecated here
  V8_DEPRECATED(\"Use maybe version\", uint32_t Uint32Value() const);
  ^
/Users/Ajay/.node-gyp/10.15.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/ursaNative.cc:730:28: warning: 'Uint32Value' is deprecated [-Wdeprecated-declarations]
    int padding = args[1]->Uint32Value();
                           ^
/Users/Ajay/.node-gyp/10.15.1/include/node/v8.h:2477:3: note: 'Uint32Value' has been explicitly marked deprecated here
  V8_DEPRECATED(\"Use maybe version\", uint32_t Uint32Value() const);
  ^
/Users/Ajay/.node-gyp/10.15.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/ursaNative.cc:776:28: warning: 'Uint32Value' is deprecated [-Wdeprecated-declarations]
    int padding = args[1]->Uint32Value();
                           ^
/Users/Ajay/.node-gyp/10.15.1/include/node/v8.h:2477:3: note: 'Uint32Value' has been explicitly marked deprecated here
  V8_DEPRECATED(\"Use maybe version\", uint32_t Uint32Value() const);
  ^
/Users/Ajay/.node-gyp/10.15.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/ursaNative.cc:822:28: warning: 'Uint32Value' is deprecated [-Wdeprecated-declarations]
    int padding = args[1]->Uint32Value();
                           ^
/Users/Ajay/.node-gyp/10.15.1/include/node/v8.h:2477:3: note: 'Uint32Value' has been explicitly marked deprecated here
  V8_DEPRECATED(\"Use maybe version\", uint32_t Uint32Value() const);
  ^
/Users/Ajay/.node-gyp/10.15.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/ursaNative.cc:928:24: warning: 'Uint32Value' is deprecated [-Wdeprecated-declarations]
    int nid = args[0]->Uint32Value();
                       ^
/Users/Ajay/.node-gyp/10.15.1/include/node/v8.h:2477:3: note: 'Uint32Value' has been explicitly marked deprecated here
  V8_DEPRECATED(\"Use maybe version\", uint32_t Uint32Value() const);
  ^
/Users/Ajay/.node-gyp/10.15.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/ursaNative.cc:982:24: warning: 'Uint32Value' is deprecated [-Wdeprecated-declarations]
    int nid = args[0]->Uint32Value();
                       ^
/Users/Ajay/.node-gyp/10.15.1/include/node/v8.h:2477:3: note: 'Uint32Value' has been explicitly marked deprecated here
  V8_DEPRECATED(\"Use maybe version\", uint32_t Uint32Value() const);
  ^
/Users/Ajay/.node-gyp/10.15.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/ursaNative.cc:1044:24: warning: 'Uint32Value' is deprecated [-Wdeprecated-declarations]
    int nid = args[0]->Uint32Value();
                       ^
/Users/Ajay/.node-gyp/10.15.1/include/node/v8.h:2477:3: note: 'Uint32Value' has been explicitly marked deprecated here
  V8_DEPRECATED(\"Use maybe version\", uint32_t Uint32Value() const);
  ^
/Users/Ajay/.node-gyp/10.15.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/ursaNative.cc:1065:25: warning: 'Uint32Value' is deprecated [-Wdeprecated-declarations]
    int sLen = args[2]->Uint32Value();
                        ^
/Users/Ajay/.node-gyp/10.15.1/include/node/v8.h:2477:3: note: 'Uint32Value' has been explicitly marked deprecated here
  V8_DEPRECATED(\"Use maybe version\", uint32_t Uint32Value() const);
  ^
/Users/Ajay/.node-gyp/10.15.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/ursaNative.cc:1102:24: warning: 'Uint32Value' is deprecated [-Wdeprecated-declarations]
    int nid = args[0]->Uint32Value();
                       ^
/Users/Ajay/.node-gyp/10.15.1/include/node/v8.h:2477:3: note: 'Uint32Value' has been explicitly marked deprecated here
  V8_DEPRECATED(\"Use maybe version\", uint32_t Uint32Value() const);
  ^
/Users/Ajay/.node-gyp/10.15.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/ursaNative.cc:1135:25: warning: 'Uint32Value' is deprecated [-Wdeprecated-declarations]
    int sLen = args[3]->Uint32Value();
                        ^
/Users/Ajay/.node-gyp/10.15.1/include/node/v8.h:2477:3: note: 'Uint32Value' has been explicitly marked deprecated here
  V8_DEPRECATED(\"Use maybe version\", uint32_t Uint32Value() const);
  ^
/Users/Ajay/.node-gyp/10.15.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/ursaNative.cc:1218:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->n = modulus;
                ^
/Users/Ajay/.node-gyp/10.15.1/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1219:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->e = exponent;
                ^
/Users/Ajay/.node-gyp/10.15.1/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1220:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->p = p;
                ^
/Users/Ajay/.node-gyp/10.15.1/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1221:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->q = q;
                ^
/Users/Ajay/.node-gyp/10.15.1/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1222:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->dmp1 = dp;
                ^
/Users/Ajay/.node-gyp/10.15.1/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1223:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->dmq1 = dq;
                ^
/Users/Ajay/.node-gyp/10.15.1/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1224:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->iqmp = inverseQ;
                ^
/Users/Ajay/.node-gyp/10.15.1/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1225:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->d = d;
                ^
/Users/Ajay/.node-gyp/10.15.1/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1270:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->n = modulus;
                ^
/Users/Ajay/.node-gyp/10.15.1/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1271:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->e = exponent;
                ^
/Users/Ajay/.node-gyp/10.15.1/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
12 warnings and 16 errors generated.
make: *** [Release/obj.target/ursaNative/src/ursaNative.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/Ajay/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command \"/Users/Ajay/.nvm/versions/node/v10.15.1/bin/node\" \"/Users/Ajay/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /Users/Ajay/Sites/Merch/comlib/node_modules/ursa
```

node -e 'console.log(process.platform, process.arch, process.versions.node)' 
Output:
`darwin x64 10.15.1`

**Comment by raymondfeng** [comment]
@AjayPoshak We're waiting for https://github.com/JoshKaufman/ursa to publish a new version to support Node 10.x.

BTW, `ursa` is an optional dependency and failure to install it can be ignored for most applications.

**Comment by AjayPoshak** [comment]
Cool, then I'll go ahead and use it on Node 10.
