### ISSUE TITLE
Fault thrown when using WSSecurityCert

### ISSUE THREAD

**Issue by milesje** [strongloop/strong-soap#225]
# Description/Steps to reproduce
Making a Client call works until WSSecurityCert is added.

```
var privateKey = fs.readFileSync(properties.get("ssl.private.key"));
var publicKey = fs.readFileSync(properties.get("ssl.public.key"));
var password = properties.get("x509.storePassword")
var wsSecurity = new soap.WSSecurityCert(privateKey, publicKey, password, 'utf8');
soap.createClient(stageWSDL, clientOptions, function (err, client) {
    client.setSecurity(wsSecurity);
    var xml = fs.readFileSync("C:\\Users\\jmiles\\Desktop\\iCON EFile\\Good_NCAC.XML").toString();
    var json = xmlHandler.xmlToJson(null, xml, null)
    var response = json.Body.NotifyCaseAssignmentComplete;
    client.NotifyCaseAssignmentComplete(response, function (err, result, envelope, soapHeader) {
        if (err){
            console.log("Error sending NotifyCaseAssignmentComplete")
            console.log(err);
        }
        console.log('result: ',result)
        console.log(envelope)
        var ret = xmlHandler.xmlToJson(null, envelope, null)
        console.log(JSON.stringify(ret, null, 2))
    })
});
```

# Expected result
I would expect the call to work the same both without and with the WSSecurityCert set.

```
{ Error: faultcode: S:Server faultstring: com.ctc.wstx.exc.WstxParsingException: Non-default namespace can not map to empty URI (as per Namespace 1.0 # 2) in XML 1.0 documents
 at [row,col {unknown-source}]: [33,52]
    at XMLHandler.xmlToJson (C:\Users\jmiles\code\eFile\eFileNode\node_modules\strong-soap\src\parser\xmlHandler.js:726:23)
    at C:\Users\jmiles\code\eFile\eFileNode\node_modules\strong-soap\src\client.js:284:28
    at Request._callback (C:\Users\jmiles\code\eFile\eFileNode\node_modules\strong-soap\src\http.js:136:9)
    at Request.self.callback (C:\Users\jmiles\code\eFile\eFileNode\node_modules\request\request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (C:\Users\jmiles\code\eFile\eFileNode\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (C:\Users\jmiles\code\eFile\eFileNode\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
  root: { Envelope: { Body: [Object] } },
  response:
   IncomingMessage {
     _readableState:
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: BufferList { head: null, tail: null, length: 0 },
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        emitClose: true,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: true,
        decoder: null,
        encoding: null },
     readable: false,
     _events:
      { end: [Array],
        close: [Array],
        data: [Function],
        error: [Function] },
     _eventsCount: 4,
     _maxListeners: undefined,
     socket:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [TCP],
        _parent: null,
        _host: 'localhost',
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [ClientRequest],
        [Symbol(asyncId)]: 37,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0 },
     connection:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [TCP],
        _parent: null,
        _host: 'localhost',
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [ClientRequest],
        [Symbol(asyncId)]: 37,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0 },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers:
      { 'content-type': 'text/xml;charset=utf-8',
        'transfer-encoding': 'chunked',
        date: 'Mon, 03 Jun 2019 19:58:25 GMT',
        connection: 'close' },
     rawHeaders:
      [ 'Content-Type',
        'text/xml;charset=utf-8',
        'Transfer-Encoding',
        'chunked',
        'Date',
        'Mon, 03 Jun 2019 19:58:25 GMT',
        'Connection',
        'close' ],
     trailers: {},
     rawTrailers: [],
     aborted: false,
     upgrade: false,
     url: '',
     method: null,
     statusCode: 500,
     statusMessage: '',
     client:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [TCP],
        _parent: null,
        _host: 'localhost',
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [ClientRequest],
        [Symbol(asyncId)]: 37,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0 },
     _consuming: false,
     _dumped: false,
     req:
      ClientRequest {
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Socket],
        connection: [Socket],
        _header:
         'POST /EFileTester/FilingReviewMDEService HTTP/1.1\r\nUser-Agent: strong-soap/1.19.1\r\nAccept: text/html,application/xhtml+xml,application/xml,text/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding:
none\r\nAccept-Charset: utf-8\r\nConnection: close\r\nHost: localhost:8080\r\nContent-Length: 15624\r\nContent-Type: text/xml; charset=utf-8\r\nSOAPAction: ""\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/EFileTester/FilingReviewMDEService',
        _ended: true,
        res: [Circular],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     request:
      Request {
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        uri: [Url],
        method: 'POST',
        headers: [Object],
        followAllRedirects: true,
        body:
         '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">\n  <soap:Header>\n    <wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" soap:mustUnderstand="1">\n
 <wsse:BinarySecurityToken EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary" ValueType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3" wsu:Id="x509-645dca01be524bdcb5d69be00821d5f2">Bag Attributes    friendlyName: hopkinscountyonline.net    localKeyID: 54 69 6D 65 20 31 35 35 39 31 34 36 37 33 31 32 33 39 subject=OU = Domain Control Validated, CN = hopkinscountyonline.netissuer=C = US, ST = Arizona, L = Scottsdale, O = "GoDaddy.com, Inc.", OU = http://certs.godaddy.com/repository/, CN = Go Daddy Secure Certificate Authority - G2MIIGWzCCBUOgAwIBAgIJAOFzG/24rlrlMA0GCSqGSIb3DQEBCwUAMIG0MQswCQYDVQQGEwJVUzEQMA4GA1UECBMHQXJpem9uYTETMBEGA1UEBxMKU2NvdHRzZGFsZTEaMBgGA1UEChMRR29EYWRkeS5jb20sIEluYy4xLTArBgNVBAsTJGh0dHA6Ly9jZXJ0cy5nb2RhZGR5LmNvbS9yZXBvc2l0b3J5LzEzMDEGA1UEAxMqR28gRGFkZHkgU2VjdXJlIENlcnRpZmljYXRlIEF1dGhvcml0eSAtIEcyMB4XDTE5MDQyNDE2MTIzMVoXDTIwMDQyNDE2MTIzMVowRTEhMB8GA1UECxMYRG9tYWluIENvbnRyb2wgVmFsaWRhdGVkMSAwHgYDVQQDExdob3BraW5zY291bnR5b25saW5lLm5ldDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALuyVkRzQc/fwnjoyIwU15cZ4w4+KMZIOXH86O7rI9Y2ZqmEAmCFDd8+HjKuDfMJvgcDlUEjzM6smow7CQfJQG6MWS2wIMEViYSVSQ4SpFuSeDX/0K6QuBRVuSwxN35OchIcbIOOs+50Mec35HKkp4hgOCUotNvl9MiidheMiTiJxz4rNq44RGqETGhAErWwkvmORCUJZza67t08yOOGxl0Q4IfglbvIpF/olCRVTfI7mcY8boUXJ0yQHCblpUAMUzMjCCwKBMqCxsY66m24sw7PkNUHCgElm3073X5bbMmplaxpZmvk+xUa5NmQOxUYB7KRyTK7IIGCc2fUQUFGmskCAwEAAaOCAtwwggLYMAwGA1UdEwEB/wQCMAAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMA4GA1UdDwEB/wQEAwIFoDA4BgNVHR8EMTAvMC2gK6AphidodHRwOi8vY3JsLmdvZGFkZHkuY29tL2dkaWcyczEtMTA3Mi5jcmwwXQYDVR0gBFYwVDBIBgtghkgBhv1tAQcXATA5MDcGCCsGAQUFBwIBFitodHRwOi8vY2VydGlmaWNhdGVzLmdvZGFkZHkuY29tL3JlcG9zaXRvcnkvMAgGBmeBDAECATB2BggrBgEFBQcBAQRqMGgwJAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmdvZGFkZHkuY29tLzBABggrBgEFBQcwAoY0aHR0cDovL2NlcnRpZmljYXRlcy5nb2RhZGR5LmNvbS9yZXBvc2l0b3J5L2dkaWcyLmNydDAfBgNVHSMEGDAWgBRAwr0njsw0gzCiM9f7bLPwtCyAzjA/BgNVHREEODA2ghdob3BraW5zY291bnR5b25saW5lLm5ldIIbd3d3LmhvcGtpbnNjb3VudHlvbmxpbmUubmV0MB0GA1UdDgQWBBSUh3hCWY13H2JQxrr1guszilriFjCCAQUGCisGAQQB1nkCBAIEgfYEgfMA8QB3AKS5CZC0GFgUh7sTosxncAo8NZgE+RvfuON3zQ7IDdwQAAABalAevHUAAAQDAEgwRgIhALZ5t/mH6ZNHA2G8P0m0dOakDQ6Vs5eZpMvC6bp9VHQkAiEA473W6nWa1/AQ0Annkw1lKlqZc6BY2IKJHms0of4VKIoAdgBep3P531bA57U2SH3QSeAyepGaDIShEhKEGHWWgXFFWAAAAWpQHsFQAAAEAwBHMEUCIQDC6ZSPxnE1u2fjP+Jw4weAMHYjvinKk8uXH9XNwpW/8wIgWBYKkVDYY/PfKnjamYJFAaI/ncQc2wLo/ectlvqaVsgwDQYJKoZIhvcNAQELBQADggEBABktyCPlGECg7ZQ6dwUVaf7iQVCaszKhpuA+xVB2Fiwrp1K+t+Jm/1DWYMyaJOIbhQPRX3iP7pdTeo7Bhx4P3ABd8geKlCYFnAytNbqX7xcu1pIHopB36cC/cPkt+EjGLjkat9ejDcfO/4R5SKW0rkjnVlqp952198OHs+vhORV5+Znx2Te3oKVLi1g4KHh2mOpORexiVmhWyRbXyhK4Gzn2XFb4Imdv7qBGHCcT/G88/EIEyzAtd/06Xpk6/aPBL84ne7bljF39iUjtf/1+pIPrkqAwhee0UTkRt7Q082pQiguCiHJCk0tbULUBLIsCw6CzpZy0iOK4NClqbgYrXYU=Bag Attributes    friendlyName: CN=Go Daddy Secure Certificate Authority - G2,OU=http://certs.godaddy.com/repository/,O=GoDaddy.com\\, Inc.,L=Scottsdale,ST=Arizona,C=USsubject=C = US, ST = Arizona, L = Scottsdale, O = "GoDaddy.com, Inc.", OU = http://certs.godaddy.com/repository/, CN = Go Daddy Secure Certificate Authority - G2issuer=C = US, ST = Arizona,
L = Scottsdale, O = "GoDaddy.com, Inc.", CN = Go Daddy Root Certificate Authority - G2-----BEGIN CERTIFICATE-----MIIE0DCCA7igAwIBAgIBBzANBgkqhkiG9w0BAQsFADCBgzELMAkGA1UEBhMCVVMxEDAOBgNVBAgTB0FyaXpvbmExEzARBgNVBAcTClNjb3R0c2RhbGUxGjAYBgNVBAoTEUdvRGFkZHkuY29tLCBJbmMuMTEwLwYDVQQDEyhHbyBEYWRkeSBSb290IENlcnRpZmljYXRlIEF1dGhvcml0eSAtIEcyMB4XDTExMDUwMzA3MDAwMFoXDTMxMDUwMzA3MDAwMFowgbQxCzAJBgNVBAYTAlVTMRAwDgYDVQQIEwdBcml6b25hMRMwEQYDVQQHEwpTY290dHNkYWxlMRowGAYDVQQKExFHb0RhZGR5LmNvbSwgSW5jLjEtMCsGA1UECxMkaHR0cDovL2NlcnRzLmdvZGFkZHkuY29tL3JlcG9zaXRvcnkvMTMwMQYDVQQDEypHbyBEYWRkeSBTZWN1cmUgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IC0gRzIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC54MsQ1K92vdSTYuswZLiBCGzDBNliF44v/z5lz4/OYuY8UhzaFkVLVat4a2ODYpDOD2lsmcgaFItMzEUz6ojcnqOvK/6AYZ15V8TPLvQ/MDxdR/yaFrzDN5ZBUY4RS1T4KL7QjL7wMDge87Am+GZHY23ecSZHjzhHU9FGHbTj3ADqRay9vHHZqm8A29vNMDp5T19MR/gd71vCxJ1gO7GyQ5HYpDNO6rPWJ0+tJYqlxvTV0KaudAVkV4i1RFXULSo6Pvi4vekyCgKUZMQWOlDxSq7neTOvDCAHf+jfBDnCaQJsY1L6d8EbyHSHyLmTGFBUNUtpTrw700kuH9zB0lL7AgMBAAGjggEaMIIBFjAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBBjAdBgNVHQ4EFgQUQMK9J47MNIMwojPX+2yz8LQsgM4wHwYDVR0jBBgwFoAUOpqFBxBnKLbv9r0FQW4gwZTaD94wNAYIKwYBBQUHAQEEKDAmMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5nb2RhZGR5LmNvbS8wNQYDVR0fBC4wLDAqoCigJoYkaHR0cDovL2NybC5nb2RhZGR5LmNvbS9nZHJvb3QtZzIuY3JsMEYGA1UdIAQ/MD0wOwYEVR0gADAzMDEGCCsGAQUFBwIBFiVodHRwczovL2NlcnRzLmdvZGFkZHkuY29tL3JlcG9zaXRvcnkvMA0GCSqGSIb3DQEBCwUAA4IBAQAIfmyTEMg4uJapkEv/oV9PBO9sPpyIBslQj6Zz91cxG7685C/b+LrTW+C05+Z5Yg4MotdqY3MxtfWoSKQ7CC2iXZDXtHwlTxFWMMS2RJ17LJ3lXubvDGGqv+QqG+6EnriDfcFDzkSnE3ANkR/0yBOtg2DZ2HKocyQetawiDsoXiWJYRBuriSUBAA/NxBti21G00w9RKpv0vHP8ds42pM3Z2Czqrpv1KrKQ0U11GIo/ikGQI31bS/6kA1ibRrLDYGCD+H1QQc7CoZDDu+8CL9IVVO5EFdkKrqeKM+2xLXY2JtwE65/3YR8V3Idv7kaWKK2hJn0KCacuBKONvPi8BDAB-----END CERTIFICATE-----Bag Attributes    friendlyName: CN=Go Daddy Root Certificate Authority - G2,O=GoDaddy.com\\, Inc.,L=Scottsdale,ST=Arizona,C=USsubject=C = US, ST = Arizona, L = Scottsdale, O = "GoDaddy.com, Inc.", CN = Go Daddy Root Certificate Authority - G2issuer=C = US, ST = Arizona, L = Scottsdale, O = "GoDaddy.com, Inc.", CN = Go Daddy Root Certificate Authority - G2-----BEGIN CERTIFICATE-----MIIDxTCCAq2gAwIBAgIBADANBgkqhkiG9w0BAQsFADCBgzELMAkGA1UEBhMCVVMxEDAOBgNVBAgTB0FyaXpvbmExEzARBgNVBAcTClNjb3R0c2RhbGUxGjAYBgNVBAoTEUdvRGFkZHkuY29tLCBJbmMuMTEwLwYDVQQDEyhHbyBEYWRkeSBSb290IENlcnRpZmljYXRlIEF1dGhvcml0eSAtIEcyMB4XDTA5MDkwMTAwMDAwMFoXDTM3MTIzMTIzNTk1OVowgYMxCzAJBgNVBAYTAlVTMRAwDgYDVQQIEwdBcml6b25hMRMwEQYDVQQHEwpTY290dHNkYWxlMRowGAYDVQQKExFHb0RhZGR5LmNvbSwgSW5jLjExMC8GA1UEAxMoR28gRGFkZHkgUm9vdCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkgLSBHMjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAL9xYgjx+lk09xvJGKP3gElY6SKDE6bFIEMBO4Tx5oVJnyfq9oQbTqC023CYxzIBsQU+B07u9PpPL1kwIuerGVZr4oAH/PMWdYA5UXvl+TW2dE6pjYIT5LY/qQOD+qK+ihVqf94Lw7YZFAXK6sOoBJQ7RnwyDfMAZiLIjWltNowRGLfTshxgtDj6AozO091GB94KPutdfMh8+7ArU6SSYmlRJQVhGkSBjCypQ5Yj36w6gZoOKcUcqeldHraenjAKOc7xiID7S13MMuyFYkMlNAJWJwGRtDtwKj9useiciAF9n9T521NtYJ2/LOdYq7hfRvzOxBsDPAnrSTFcaUaz4EcCAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYEFDqahQcQZyi27/a9BUFuIMGU2g/eMA0GCSqGSIb3DQEBCwUAA4IBAQCZ21151fmXWWcDYfF+OwYxdS2hII5PZYe096acvNjpL9DbWu7PdIxztDhC2gV7+AJ1uP2lsdeu9tfeE8tTEH6KRtGX+rcuKxGrkLAngPnon1rpN5+r5N9ss4UXnT3ZJE95kTXWXwTrgIOrmgIttRD02JDHBHNA7XIloKmf7J6raBKZV8aPEjoJpL1E/QYVN8Gb5DKj7Tjo2GTzLH4U/ALqn83/B2gX2yKQOC16jdFU8WnjXzPKej17CuPKf1855eJ1usV2GDPOLPAvTK33sefOT6jEm0pUBsV/fdUID+Ic/n4XuKxe9tQWskMJDE32p2u0mYRlynqI4uJEvlz36hz1-----END CERTIFICATE-----</wsse:BinarySecurityToken>\n      <wsu:Timestamp wsu:Id="_1">\n        <wsu:Created>2019-06-03T19:58:25Z</wsu:Created>\n        <wsu:Expires>2019-06-03T20:08:25Z</wsu:Expires>\n      </wsu:Timestamp>\n      <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">\n        <SignedInfo>\n          <CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>\n          <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>\n          <Reference URI="#_0">\n            <Transforms>\n              <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>\n              <Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>\n            </Transforms>\n            <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>\n            <DigestValue>IjPpHKw2/IVN749j+4OubLwxmzw=</DigestValue>\n          </Reference>\n          <Reference URI="#_1">\n            <Transforms>\n              <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>\n              <Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>\n            </Transforms>\n            <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>\n            <DigestValue>31RNAYsPaUvCWaSBg2yA5XfjAzw=</DigestValue>\n          </Reference>\n        </SignedInfo>\n        <SignatureValue>b9XmO2IalRTFBQrjzdUy0LfqbuWu7glBOgLe4UlxdzTp4ICXVEQ/q/HC5eXpbjYxiysUXaTtu/v3tO+4gDJ6MjFtQydxXxXOCqA78iYuZ5uR2iDxnOo124l73jp+Z6jytENDqY5lkWdkIMzRWt7owURnWczXoAA+QAqhtngf2WAd3E2oNvsA2rb4gfxr04b83iEhorbbjfm+zkU3dfqQ5XFVtifuQ5AgB6cjxvGY6DlphikpmeOqX5JXY7HEIHbU7xBkXvOs1kg7PtzGEUd5Mw/z5qqgGZn6OwUP3DXRUnp3gwGinxFZ3P2oV3d466Dwq9hwWKjydcjYa33zlIzOyA==</SignatureValue>\n        <KeyInfo>\n          <wsse:SecurityTokenReference xmlns:wsse="">\n            <wsse:Reference URI="x509-645dca01be524bdcb5d69be00821d5f2" ValueType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3"/>\n          </wsse:SecurityTokenReference>\n        </KeyInfo>\n      </Signature>\n    </wsse:Security>\n  </soap:Header>\n  <soap:Body>\n    <ns1:NotifyCaseAssignmentComplete xmlns:ns1="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitions-4.0">\n      <NotifyCaseAssignmentCompleteRequest>\n        <CreateCaseCallbackMessage schemaLocation="urn:tyler:ecf:extensions:CreateCaseCallbackMessage ..\\..\\..\\Schema\\Extension\\CreateCaseCallbackMessage.xsd">\n          <SendingMDELocationID>\n            <IdentificationID>https://courtrecordmde.com</IdentificationID>\n          </SendingMDELocationID>\n          <SendingMDEProfileCode>urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:WebServicesMessaging-2.0</SendingMDEProfileCode>\n          <CivilCase schemaLocation="urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:CivilCase-4.0 ..\\..\\..\\Schema\\ECF\\casetype\\ECF-4.0-CivilCase.xsd">\n            <CaseTitleText>INJURY OR DAMAGE WITH MV</CaseTitleText>\n            <CaseCategoryText>2</CaseCategoryText>\n            <CaseTrackingID>CV44046</CaseTrackingID>\n            <CaseDocketID>CV44046</CaseDocketID>\n            <CaseAugmentation>\n              <CaseCourt>\n                <OrganizationIdentification>\n
                <IdentificationID>hopkins:dc</IdentificationID>\n                </OrganizationIdentification>\n              </CaseCourt>\n              <CaseJudge>\n                <JudicialOfficialBarMembership>\n                  <JudicialOfficialBarIdentification>\n                    <IdentificationID>000</IdentificationID>\n                    <IdentificationCategoryText>JUDGEID</IdentificationCategoryText>\n                  </JudicialOfficialBarIdentification>\n                </JudicialOfficialBarMembership>\n              </CaseJudge>\n              <CaseLineageCase>\n
        <CaseTrackingID>c1f3ec11-3643-444a-bff9-5f35cc396c81</CaseTrackingID>\n              </CaseLineageCase>\n            </CaseAugmentation>\n            <CaseAugmentation schemaLocation="urn:tyler:ecf:extensions:Common ..\\..\\..\\Schema\\Substitution\\Tyler.xsd">\n              <CaseOtherEntityAttorney>\n                <RoleOfPersonReference ref="Attorney1"/>\n                <CaseRepresentedPartyReference ref="Party1"/>\n              </CaseOtherEntityAttorney>\n              <CaseOtherEntityAttorney>\n                <RoleOfPersonReference ref="Attorney2"/>\n                <CaseRepresentedPartyReference ref="Party2"/>\n              </CaseOtherEntityAttorney>\n              <CaseParticipant>\n                <EntityPerson id="Party1">\n                  <PersonOtherIdentification>\n                    <IdentificationID>b72214aa-45b9-4ff9-8b41-475bb0cdbc0c</IdentificationID>\n                    <IdentificationCategoryText>PARTYID</IdentificationCategoryText>\n
            </PersonOtherIdentification>\n                  <PersonOtherIdentification>\n                    <IdentificationID>b72214aa-45b9-4ff9-8b41-475bb0cdbc0c</IdentificationID>\n
      <IdentificationCategoryText>CMSID</IdentificationCategoryText>\n                  </PersonOtherIdentification>\n                </EntityPerson>\n                <CaseParticipantRoleCode>P</CaseParticipantRoleCode>\n              </CaseParticipant>\n              <CaseParticipant>\n                <EntityPerson id="Party2">\n                  <PersonOtherIdentification>\n
   <IdentificationID>9dd3a16d-1797-4563-9365-a04be09c3dab</IdentificationID>\n                    <IdentificationCategoryText>PARTYID</IdentificationCategoryText>\n                  </PersonOtherIdentification>\n                  <PersonOtherIdentification>\n                    <IdentificationID>9dd3a16d-1797-4563-9365-a04be09c3dab</IdentificationID>\n                    <IdentificationCategoryText>CMSID</IdentificationCategoryText>\n                  </PersonOtherIdentification>\n                </EntityPerson>\n                <CaseParticipantRoleCode>P</CaseParticipantRoleCode>\n
         </CaseParticipant>\n              <CaseParticipant>\n                <EntityPerson id="Party3">\n                  <PersonOtherIdentification>\n                    <IdentificationID>dfed6d1a-1947-4270-9792-b21611ca07d8</IdentificationID>\n                    <IdentificationCategoryText>PARTYID</IdentificationCategoryText>\n                  </PersonOtherIdentification>\n
    <PersonOtherIdentification>\n                    <IdentificationID>dfed6d1a-1947-4270-9792-b21611ca07d8</IdentificationID>\n                    <IdentificationCategoryText>CMSID</IdentificationCategoryText>\n                  </PersonOtherIdentification>\n                </EntityPerson>\n                <CaseParticipantRoleCode>D</CaseParticipantRoleCode>\n              </CaseParticipant>\n              <CaseParticipant>\n                <EntityPerson id="Attorney1">\n                  <PersonOtherIdentification>\n                    <IdentificationID>888401fe-547b-4600-b64b-66889a5d464d</IdentificationID>\n                    <IdentificationCategoryText>ATTORNEYID</IdentificationCategoryText>\n                  </PersonOtherIdentification>\n                  <PersonOtherIdentification>\n                    <IdentificationID>07966900</IdentificationID>\n                    <IdentificationCategoryText>CMSID</IdentificationCategoryText>\n                  </PersonOtherIdentification>\n                </EntityPerson>\n                <CaseParticipantRoleCode>ATTY</CaseParticipantRoleCode>\n              </CaseParticipant>\n              <CaseParticipant>\n
   <EntityPerson id="Attorney2">\n                  <PersonOtherIdentification>\n                    <IdentificationID>d21cab61-7a31-4531-bf7e-8b46b91db43a</IdentificationID>\n                    <IdentificationCategoryText>ATTORNEYID</IdentificationCategoryText>\n                  </PersonOtherIdentification>\n                  <PersonOtherIdentification>\n                    <IdentificationID>07966900</IdentificationID>\n                    <IdentificationCategoryText>CMSID</IdentificationCategoryText>\n                  </PersonOtherIdentification>\n                </EntityPerson>\n
              <CaseParticipantRoleCode>ATTY</CaseParticipantRoleCode>\n              </CaseParticipant>\n              <CaseTypeText>S011-1</CaseTypeText>\n            </CaseAugmentation>\n
   <CauseOfActionCode/>\n            <ClassActionIndicator>false</ClassActionIndicator>\n            <JuryDemandIndicator>false</JuryDemandIndicator>\n            <ReliefTypeCode/>\n          </CivilCase>\n        </CreateCaseCallbackMessage>\n      </NotifyCaseAssignmentCompleteRequest>\n    </ns1:NotifyCaseAssignmentComplete>\n  </soap:Body>\n</soap:Envelope>',
        callback: [Function],
        readable: true,
        writable: true,
        explicitMethod: true,
        _qs: [Querystring],
        _auth: [Auth],
        _oauth: [OAuth],
        _multipart: [Multipart],
        _redirect: [Redirect],
        _tunnel: [Tunnel],
        setHeader: [Function],
        hasHeader: [Function],
        getHeader: [Function],
        removeHeader: [Function],
        localAddress: undefined,
        pool: {},
        dests: [],
        __isRequestRequest: true,
        _callback: [Function],
        proxy: null,
        tunnel: false,
        setHost: false,
        originalCookieHeader: undefined,
        _disableCookies: true,
        _jar: undefined,
        port: '8080',
        host: 'localhost',
        path: '/EFileTester/FilingReviewMDEService',
        httpModule: [Object],
        agentClass: [Function],
        agent: [Agent],
        _started: true,
        href: 'http://localhost:8080/EFileTester/FilingReviewMDEService',
        req: [ClientRequest],
        ntick: true,
        response: [Circular],
        originalHost: 'localhost:8080',
        originalHostHeaderName: 'Host',
        responseContent: [Circular],
        _destdata: true,
        _ended: true,
        _callbackCalled: true },
     toJSON: [Function: responseToJSON],
     caseless: Caseless { dict: [Object] },
     body:
      '<?xml version=\'1.0\' encoding=\'UTF-8\'?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><S:Fault xmlns:ns4="http://www.w3.org/2003/05/soap-envelope"><faultcode>S:Server</faultcode><faultstring>com.ctc.wstx.exc.WstxParsingException: Non-default namespace can not map to empty URI (as per Namespace 1.0 # 2) in XML 1.0 documents&#xD;\n at [row,col {unknown-source}]: [33,52]</faultstring></S:Fault></S:Body></S:Envelope>' },
  body:
   '<?xml version=\'1.0\' encoding=\'UTF-8\'?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><S:Fault xmlns:ns4="http://www.w3.org/2003/05/soap-envelope"><faultcode>S:Server</faultcode><faultstring>com.ctc.wstx.exc.WstxParsingException: Non-default namespace can not map to empty URI (as per Namespace 1.0 # 2) in XML 1.0 documents&#xD;\n at [row,col {unknown-source}]: [33,52]</faultstring></S:Fault></S:Body></S:Envelope>' }
```

**Comment by milesje** [comment]
I'm closing this as I think it might be an issue with having the servers security configured incorrectly.

**Comment by smile4me1974** [comment]
can yu wrap this up in my terms
