### ISSUE TITLE
Module {{ursa}} must be installed

### ISSUE THREAD

**Issue by milesje** [strongloop/strong-soap#227]
I'm getting this error when I run, but I do have uRSA installed.
```
/home/JMILES/eFileNode/node_modules/strong-soap/src/security/WSSecurityCert.js:46
      throw new Error(g.f('Module {{ursa}} must be installed to use {{WSSecurityCert}}'));
      ^

Error: Module ursa must be installed to use WSSecurityCert
    at new WSSecurityCert (/home/JMILES/eFileNode/node_modules/strong-soap/src/security/WSSecurityCert.js:46:13)
    at Object.<anonymous> (/home/JMILES/eFileNode/index.js:29:18)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```
```
ls node_modules/ursa/
LICENSE.txt   README.md     binding.gyp   build         lib           package.json  src           test
```

**Comment by milesje** [comment]
If I modify node_modes/strong-soap/src/security/WSSecurityCert.js and change the optional('strong-ursa') to optional('ursa') it works as expected.

**Comment by raymondfeng** [comment]
Please try latest version of `strong-soap`. The dependency of `strong-ursa` or `ursa` is removed.

**Comment by milesje** [comment]
Awesome that works... I had to tweak the code a little as I was getting a error about Passphrase not being supported, but that was an easy change.
