### ISSUE TITLE
Babel script doesn't run in one of the CI build targets

### ISSUE THREAD

**Issue by rashmihunt** [strongloop/strong-soap#29]
Strong-soap installs and tests strongloop-soap-connector as well as part of it’s CI build ' [cis-jenkins] downstream: loopback-connector-soap@master” Babel script seem to have not run for strong-soap in this case.

Error: Cannot find module './lib/security/index'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/jenkins/workspace/ds/loopback-connector-soap~master/node_modules/strong-soap/index.js:10:23)

https://cis-jenkins.swg-devops.com/job/ds/job/loopback-connector-soap~master/126/
https://cis-jenkins.swg-devops.com/job/ds/job/loopback-connector-soap~master/126/consoleFull#-207526304206f8fc75-e0b9-479e-b471-e8fe633361ff

**Comment by rashmihunt** [comment]
Closing since loopback-connector-soap CI builds are clean.
