### ISSUE TITLE
ReferenceError: definitions is not defined

### ISSUE THREAD

**Issue by miickel** [strongloop/strong-soap#31]
Hi!

This module seems like the perfect fit for a project I'm working on.

However, when trying to run a simple `client.describe()` on the wsdl [which you can access here](https://sit-sob.test.1177.se/sob-application-api/GetProcessesResponderService?wsdl), I get this error:

```
ReferenceError: definitions is not defined
    at /Users/____/dev/_____/skl-test/node_modules/strong-soap/lib/parser/wsdl/operation.js:271:52
    at Array.forEach (native)
    at Function.describeHeaders (/Users/____/dev/_____/skl-test/node_modules/strong-soap/lib/parser/wsdl/operation.js:268:21)
    at Operation.describe (/Users/____/dev/_____/skl-test/node_modules/strong-soap/lib/parser/wsdl/operation.js:191:36)
    at Binding.describe (/Users/____/dev/_____/skl-test/node_modules/strong-soap/lib/parser/wsdl/binding.js:88:38)
    at Service.describe (/Users/____/dev/_____/skl-test/node_modules/strong-soap/lib/parser/wsdl/service.js:54:36)
    at WSDL.describeServices (/Users/____/dev/_____/skl-test/node_modules/strong-soap/lib/parser/wsdl.js:201:34)
    at Client.describe (/Users/____/dev/_____/skl-test/node_modules/strong-soap/lib/client.js:57:24)
    at /Users/____/dev/_____/skl-test/strongsoap.js:25:22
    at /Users/____/dev/_____/skl-test/node_modules/strong-soap/lib/soap.js:54:5
```

Here is the script in it's fully:

```javascript
const soap = require('strong-soap').soap;
const url = 'https://sit-sob.test.1177.se/sob-application-api/GetProcessesResponderService?wsdl';

soap.createClient(url, (err, client) => {
  console.log(client.describe());
});
```

Any ideas?

Thanks!

**Comment by hannupekka** [comment]
Yup, I'm getting this too.

**Comment by rashmihunt** [comment]
This issue is fixed using PR 33 - https://github.com/strongloop/strong-soap/pull/33

**Comment by hannupekka** [comment]
Still getting this when calling client methods.

**Comment by eddiemonge** [comment]
@hannupekka are you using version 1.1.0?

**Comment by hannupekka** [comment]
@eddiemonge seems to work with 1.1.0
