### ISSUE TITLE
ReferenceError: descriptor is not defined

### ISSUE THREAD

**Issue by Darkhogg** [strongloop/strong-soap#69]
I'm using `strong-soap` v1.1.0 to acces this service: `http://www.citram.es:50081/VENTAPREPAGOTITULO/VentaPrepagoTitulo.svc?wsdl`
I'm getting the following error:

```
ReferenceError: descriptor is not defined
    at Attribute.describe (…/node_modules/strong-soap/src/parser/xsd/attribute.js:33:7)
    at ComplexType.describe (…/node_modules/strong-soap/src/parser/xsd/complexType.js:23:31)
    at Extension.describe (…/node_modules/strong-soap/src/parser/xsd/extension.js:18:38)
    at ComplexContent.describe (…/node_modules/strong-soap/src/parser/xsd/complexContent.js:16:31)
    at ComplexType.describe (…/node_modules/strong-soap/src/parser/xsd/complexType.js:23:31)
    at Extension.describe (…/node_modules/strong-soap/src/parser/xsd/extension.js:18:38)
    at ComplexContent.describe (…/node_modules/strong-soap/src/parser/xsd/complexContent.js:16:31)
    at ComplexType.describe (…/node_modules/strong-soap/src/parser/xsd/complexType.js:23:31)
    at Element.describe (…/node_modules/strong-soap/src/parser/xsd/element.js:49:40)
    at Sequence.describeChildren (…/node_modules/strong-soap/src/parser/xsd/xsdElement.js:18:31)
    at Sequence.describe (…/node_modules/strong-soap/src/parser/xsd/xsdElement.js:27:17)
    at ComplexType.describe (…/node_modules/strong-soap/src/parser/xsd/complexType.js:23:31)
    at Element.describe (…/node_modules/strong-soap/src/parser/xsd/element.js:49:40)
    at Sequence.describeChildren (…/node_modules/strong-soap/src/parser/xsd/xsdElement.js:18:31)
    at Sequence.describe (…/node_modules/strong-soap/src/parser/xsd/xsdElement.js:27:17)
    at ComplexType.describe (…/node_modules/strong-soap/src/parser/xsd/complexType.js:23:31)
    at Element.describe (…/node_modules/strong-soap/src/parser/xsd/element.js:70:39)
    at Operation.describe (…/node_modules/strong-soap/src/parser/wsdl/operation.js:118:39)
    at Binding.describe (…/node_modules/strong-soap/src/parser/wsdl/binding.js:69:36)
    at Service.describe (…/node_modules/strong-soap/src/parser/wsdl/service.js:36:34)
    at WSDL.describeServices (…/node_modules/strong-soap/src/parser/wsdl.js:204:32)
    at Client.describe (…/node_modules/strong-soap/src/client.js:33:22)
    at TTPPlugin._callee$ (…/src/plugins/ttp-plugin.js:18:31)
    at tryCatch (…/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke [as _invoke] (…/node_modules/regenerator-runtime/runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (…/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (…/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at …/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

This is happening both in `describe()` and in any of the service methods. This particular trace is from a `describe()`, though.

**Comment by rashmihunt** [comment]
Fixed PR https://github.com/strongloop/strong-soap/pull/72
