### ISSUE TITLE
Change array prototype cause unhandled exception

### ISSUE THREAD

**Issue by alucarpd86** [strongloop/strong-soap#71]
Hi,

i've tried this module in my project and it worked properly.
Than in my code i've added to the Array prototype one function like:

```
Array.prototype.sampleFunction = function() {
	return "Sample function!";
};
```
and now the module raise an unhandled exception that cause node.js exit

```
TypeError: this.faults[f].postProcess is not a function
    at Operation.postProcess (..\node_modules\strong-soap\src\parser\wsdl\operation.js:59:22)
    at PortType.postProcess (..\node_modules\strong-soap\src\parser\wsdl\portType.js:17:13)
    at Binding.postProcess (..\node_modules\strong-soap\src\parser\wsdl\binding.js:27:16)
    at Service.postProcess (..\node_modules\strong-soap\src\parser\wsdl\service.js:20:19)
    at ..\node_modules\strong-soap\src\parser\wsdl.js:67:25
    at ..\node_modules\strong-soap\src\parser\wsdl.js:183:9
    at WSDL._processNextInclude (..\node_modules\strong-soap\src\parser\wsdl.js:151:14)
    at ..\node_modules\strong-soap\src\parser\wsdl.js:182:12
    at ..\node_modules\strong-soap\src\parser\wsdl.js:99:9
    at WSDL._processNextInclude (..\node_modules\strong-soap\src\parser\wsdl.js:151:14)
    at WSDL.processIncludes (..\node_modules\strong-soap\src\parser\wsdl.js:197:10)
    at ..\node_modules\strong-soap\src\parser\wsdl.js:54:12
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

if I remove my sampleFunction from Array the module start working again.

**Comment by rashmihunt** [comment]
@alucarpd86 Please send your javascript file which uses strong-soap module code and with the Array prototype function.

**Comment by alucarpd86** [comment]
Hi,

attached the sample javascript file

[soap.zip](https://github.com/strongloop/strong-soap/files/722925/soap.zip)

This esample doesn't even create the client object

**Comment by rashmihunt** [comment]
Fixed through PR https://github.com/strongloop/strong-soap/pull/76
